source ./functions/shard.sh
source ./functions/util/binlink.sh
source ./functions/util/notabs.sh
source ./functions/util/rec.sh
source ./functions/util/isLinux.sh
source ./functions/util/hl.sh
source ./functions/util/loop.sh
source ./functions/util/peek.sh
source ./functions/util/lookbehind.sh
source ./functions/util/pause.sh
source ./functions/util/lastfield.sh
source ./functions/util/open.sh
source ./functions/util/dictionary.sh
source ./functions/util/killport.sh
source ./functions/util/revnum.sh
source ./functions/util/checkcrlf.sh
source ./functions/util/compare.sh
source ./functions/util/show.sh
source ./functions/util/server.sh
source ./functions/util/lsfuncs.sh
source ./functions/util/argnum.sh
source ./functions/util/editlast.sh
source ./functions/util/dequote.sh
source ./functions/util/machinetype.sh
source ./functions/util/diffall.sh
source ./functions/util/appletoaststatus.sh
source ./functions/util/lll.sh
source ./functions/util/nospaces.sh
source ./functions/util/isMinGw.sh
source ./functions/util/quote.sh
source ./functions/util/appletoast.sh
source ./functions/util/isMac.sh
source ./functions/util/tp.sh
source ./functions/util/trim.sh
source ./functions/util/cputemp.sh
source ./functions/util/isCygwin.sh
source ./functions/util/weather.sh
source ./functions/refresh.sh
source ./functions/last_commits_with_string.sh
source ./functions/file_management/comic.sh
source ./functions/file_management/fullpath.sh
source ./functions/file_management/flatten.sh
source ./functions/file_management/filetype.sh
source ./functions/math/mean.sh
source ./functions/math/median.sh
source ./functions/math/math.sh
source ./functions/math/sum.sh
source ./functions/math/variance.sh
source ./functions/sysadmin/manif.sh
source ./functions/sysadmin/tosnakecase.sh
source ./functions/sysadmin/speedtest.sh
source ./functions/sysadmin/tocamelcase.sh
source ./functions/sysadmin/rederr.sh
source ./functions/sysadmin/manbook.sh
source ./functions/sysadmin/lsdaemons.sh
source ./functions/sysadmin/lastlog.sh
source ./functions/sysadmin/report.sh
source ./functions/sysadmin/psp.sh
source ./functions/sysadmin/lastmod.sh
source ./functions/sysadmin/timeclock.sh
source ./functions/sysadmin/manbash.sh
source ./functions/sysadmin/release.sh
source ./functions/sysadmin/sdk.sh
source ./functions/sysadmin/mountcd.sh
source ./functions/sysadmin/realconf.sh
source ./functions/vcs/gitflux.sh
source ./functions/vcs/mergetest.sh
source ./functions/vcs/tcommit.sh
source ./functions/vcs/resquash.sh
source ./functions/vcs/gitfile.sh
source ./functions/vcs/curr.sh
source ./functions/vcs/svn.sh
source ./functions/vcs/getbranch.sh
source ./functions/vcs/bcommit.sh
source ./functions/vcs/gitsync.sh
source ./functions/vcs/repick.sh
source ./functions/android/pasteToEmulator.sh
source ./functions/android/deeplink.sh
source ./functions/myip.sh
source ./functions/dev/kc.sh
source ./functions/dev/kr.sh
source ./functions/dev/jj.sh
source ./functions/flatten.sh
source ./functions/scriptify.sh