alias convert_list_functions="convert -list"             # list of all functions
alias convert_list="convert -list list"                  # list of all -list options
alias convert_list_channel="convert -list channel"       # list of all image -channel options
alias convert_list_command="convert -list command"       # list of all commands
alias convert_list_color="convert -list color"           # list of all color names and values
alias convert_list_colorspace="convert -list colorspace" # list of all -colorspace options
alias convert_list_compose="convert -list compose"       # list of all -compose options
alias convert_list_configure="convert -list configure"   # list of your IM version information
alias convert_list_decoration="convert -list decoration" # list of all text decorations
alias convert_list_filter="convert -list filter"         # list of all -filter options
alias convert_list_font="convert -list font"             # list of all supported fonts (on your system)
alias convert_list_format="convert -list format"         # list of all image formats
alias convert_list_gravity="convert -list gravity"       # list of all -gravity positioning options
alias convert_list_primitive="convert -list primitive"   # list of all -draw primitive shapes
alias convert_list_style="convert -list style"           # list of all text styles
alias convert_list_threshold="convert -list threshold"   # list of all dither/halftone options
alias convert_list_type="convert -list type"             # list of all image types
alias convert_list_virtual="convert -list virtual-pixel" # list of all -virtual-pixel options

alias img_resize_to_web="mogrify -resize 690\> *.png"
alias img_identify='identify -verbose'
alias img_jpgdir_to_gif="convert -delay 20 -loop 0 *.jpg myimage.gif"