about: general purpose
config:
  deps:
    docker: ""
    jq: ""
    exiftool: ""
    ffmpeg: ""
    nmap: ""
    dig: ""
    whois: ""
    mtr: ""
    tcpdump: ""
    arp-scan: ""
    rename: ""
    sqlite3: ""
    sshfs: ""
    yarn: ""
